name: example

description: A new Flutter project to demonstrate this package(mb_button).

publish_to: 'none'

version: 3.0.2+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  mb_button:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
